[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
timeout = 10
interval = 30
